### ISSUE TITLE
运行mainpro_Fer 报错 楼主可以帮我看下吗？ 谢谢Exception has occurred: TypeError can't pickle _thread._local objects

### ISSUE THREAD

**Issue by fei1213812138** [WuJie1010/Facial-Expression-Recognition.Pytorch#22]
Exception has occurred: TypeError
can't pickle _thread._local objects
  File "E:\Projects\facial-expression-recognition.pytorch-master\mainpro_fer.py", line 38, in train
    for batch_idx, (inputs, targets) in enumerate(trainloader):
  File "E:\Projects\facial-expression-recognition.pytorch-master\mainpro_fer.py", line 215, in <module>
    train(epoch)

 from ._conv import register_converters as _register_converters
==> Preparing data..
==> Building model..

Epoch: 0
learning_rate: 0.01
E:\Program Files\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Program Files\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Program Files\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by WuJie1010** [comment]
please use python2 or load the pickle file using python3

**Comment by fei1213812138** [comment]
楼主你好，我把 num_workers这个参数拿掉 就可以跑了，但是后来又遇到RuntimeError: cuda runtime error : out of memory , 我把batch size 调小，从128到64到 16，才可以跑，但是 训练很慢了，  几个小时才训练4个epoch,我的笔记本有独立显卡， GTX1050， 12G的，感觉没利用到？
![image](https://user-images.githubusercontent.com/30895175/51115174-68670180-1842-11e9-880b-c609e80c17ae.png)

**Comment by WuJie1010** [comment]
may be you can not use shared GPU? I haven't tried it in window system

**Comment by WuJie1010** [comment]
ubuntu 14.04； GTX1070； CPU: i7
