### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by XiaYuanxiang** [WuJie1010/Facial-Expression-Recognition.Pytorch#3]
博主你好，训练时python mainpro_FER.py --model VGG19 --bs 128 --lr 0.01报如下错误：
File "mainpro_FER.py", line 109, in train
    for batch_idx, (inputs, targets) in enumerate(trainloader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 174, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 198, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 34, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 82, in default_collate
    .format(type(batch[0]))))
TypeError: batch must contain tensors, numbers, or lists; found <class 'numpy.int64'>

数据加载失败？

**Comment by WuJie1010** [comment]
可能是python版本支持的问题，我用的是python2.7。您可能需要在保存数据格式的时候转换一下。

**Comment by XiaYuanxiang** [comment]
确实是，切换为python2.7就没问题了，Thanks！
