### ISSUE TITLE
Not able to load CK+ trained model present in CK+_VGG19

### ISSUE THREAD

**Issue by parantap123** [WuJie1010/Facial-Expression-Recognition.Pytorch#53]
File "visualize.py", line 43, in <module>
    net.load_state_dict(checkpoint['net'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 742, in load_state_dict
    state_dict = state_dict.copy()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'VGG' object has no attribute 'copy'
parantap@parantap-Inspiron-7548:~/codes/MTP/video_classification/codes/x/Facial-Expression-Recognition.Pytorch$ python3 visualize.py
Traceback (most recent call last):
  File "visualize.py", line 43, in <module>
    net.load_state_dict(checkpoint['net'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 742, in load_state_dict
    state_dict = state_dict.copy()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'VGG' object has no attribute 'copy'
parantap@parantap-Inspiron-7548:~/codes/MTP/video_classification/codes/x/Facial-Expression-Recognition.Pytorch$ python3 visualize.py
Traceback (most recent call last):
  File "visualize.py", line 43, in <module>
    net.load_state_dict(checkpoint['net'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 742, in load_state_dict
    state_dict = state_dict.copy()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'VGG' object has no attribute 'copy'

**Comment by LingyiC** [comment]
You can try to change `net.load_state_dict(checkpoint['net'])` to `net.load_state_dict(checkpoint['net'].state_dict())`.
I hope this helps! :-)

**Comment by WuJie1010** [comment]
I did not provide the pre-trained model for CK+

**Comment by research506** [comment]
> I did not provide the pre-trained model for CK+

Do you have that model to share on a google drive? thanks

**Comment by WuJie1010** [comment]
I have not save these models.
