### ISSUE TITLE
TypeError: h5py objects cannot be pickled

### ISSUE THREAD

**Issue by deepak-kumar-guntupu** [WuJie1010/Facial-Expression-Recognition.Pytorch#69]
Traceback (most recent call last):
  File "mainpro_FER.py", line 223, in <module>
    main()
  File "mainpro_FER.py", line 214, in main
    train(epoch)
  File "mainpro_FER.py", line 108, in train
    for batch_idx, (inputs, targets) in enumerate(trainloader):
  File "C:\Users\guntu\Anaconda3\envs\project\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\guntu\Anaconda3\envs\project\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\guntu\Anaconda3\envs\project\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\guntu\Anaconda3\envs\project\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\guntu\Anaconda3\envs\project\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\guntu\Anaconda3\envs\project\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\guntu\Anaconda3\envs\project\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\guntu\Anaconda3\envs\project\lib\site-packages\h5py\_hl\base.py", line 308, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled

can someone guide me through this error?

**Comment by Splending6** [comment]
me too

**Comment by Splending6** [comment]
It is easy.
1.In 'mainpro_FER.py' line 58,60&62, use"num_workers=0" instead
Then you will meet another error:'invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number'
2.In 'mainpro_FER.py' line 119, use"train_loss += loss.item()" instead

**Comment by Splending6** [comment]
It is easy.
1.In 'mainpro_FER.py' line 58,60&62, use"num_workers=0" instead
Then you will meet another error:'invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number'
2.In 'mainpro_FER.py' line 119,147&188, use"train_loss += loss.item()" instead
